import Image from 'next/image'
import Head from 'next/head'

import Hero from '@/components/Hero'
import BestSellers from '@/components/BestSellers'


export default function Home() {
  return (
    <div>
      <Head>
      <title>Function Project</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Navbar wrapped */}
      <Hero />
      <BestSellers />

     
      
    </div>
  )
}
